version: '3.8'

services:
  backend:
    build:
      context: ./nuevoBackend
    volumes:
      - ./nuevoBackend:/app
    container_name: fastapi_backend # <-- Actualizado para reflejar FastAPI
    ports:
      - "8001:5000" # Expone la API en el puerto 8001 del servidor
    env_file:
      - ./nuevoBackend/app/.env
      # Si en tu código de FastAPI usas alguna variable para saber si estás en producción, ponla aquí.
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/sala-de-conversacion2
      args:
        - NEXT_PUBLIC_BACKEND_URL=<ola>
    container_name: nextjs_frontend # <-- Actualizado a Next.js
    ports:
      - "8000:3000" # Expone el frontend en el puerto 8000 del servidor

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}